BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "DOENCA" (
	"ID"	VARCHAR(64) NOT NULL,
	"ID_SPECIE"	VARCHAR(64) NOT NULL,
	"NOME"	VARCHAR(64) NOT NULL,
	"IMAGE"	BLOB,
	"DESCRICAO"	TEXT,
	"CAUSAS"	TEXT,
	"TRATAMENTOS"	TEXT,
	"INFOS"	TEXT,
	FOREIGN KEY("ID_SPECIE") REFERENCES "ESPECIE"("ID"),
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "ESPECIE" (
	"ID"	VARCHAR(64) NOT NULL,
	"NOME"	VARCHAR(64) NOT NULL,
	"IMAGE"	BLOB,
	PRIMARY KEY("ID")
);
COMMIT;
